### ISSUE TITLE
Pick author not assigned

### ISSUE THREAD

**Issue by mmesim** [swiss-seismological-service/scdetect#135]
It seems that when a new pick is detected there is no author assigned 

<img width="1656" alt="Screenshot 2022-12-21 at 16 28 12" src="https://user-images.githubusercontent.com/46520311/208942353-6d3a1854-2927-49e4-9a2a-cb0532ce6f77.png">

@luca-s This might need to be fixed to be consistent with other pickers, e.g. scrtdd. Though it is not urgent.

**Comment by luca-s** [comment]
I had a look at the code and it seems that the author is set, so I need some more information to understand what is going on. Can you explain better what is your scenario? Also it would be very useful if you can dump the detected origin with `scxmldump` so that I can have a better look at the creation information of the pick.

**Comment by luca-s** [comment]
I fixed the issue on branch [fix-pick-author](https://github.com/swiss-seismological-service/scdetect/tree/fix-pick-author). IF you can give it a try I will then merge it to the `master` branch.

**Comment by mmesim** [comment]
Thanks @luca-s! It works! Go ahead with the merge and close this issue. :fireworks:
